## Series
1차원 배열 위에서 아래로 출력 idx : 데이터 

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [6]:
arr = np.arange(100, 110)
print(arr)

[100 101 102 103 104 105 106 107 108 109]


In [7]:
s = pd.Series(arr)
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int64


In [8]:
s = pd.Series(arr, dtype='int32')
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int32


In [9]:
person = ['kim', 'lee', 'park', 'hong']
s = pd.Series(person)
print(s)

0     kim
1     lee
2    park
3    hong
dtype: object


In [11]:
s = pd.Series([1, 2, 3, 4, 5, '99'])
print(s)

0     1
1     2
2     3
3     4
4     5
5    99
dtype: object


### indexing

In [12]:
person = ['kim', 'lee', 'park', 'hong']
s = pd.Series(person)

In [13]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [15]:
s[2]

'park'

In [17]:
# s[-1]

In [30]:
# s = pd.Series(person, index=['a', 'b', 'c', 'd'])# 인덱스 값 숫자아닌 문자도 가능
s = pd.Series(person, index=list('abcd'))

print(s)

a     kim
b     lee
c    park
d    hong
dtype: object


In [31]:
s['a']

'kim'

In [32]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [33]:
s.values

array(['kim', 'lee', 'park', 'hong'], dtype=object)

In [34]:
s.ndim

1

In [35]:
s.shape

(4,)

### NaN(Not a Number) - 결측치

In [37]:
s = pd.Series(person + [np.nan])
print(s)

0     kim
1     lee
2    park
3    hong
4     NaN
dtype: object


In [38]:
arr = np.arange(50, 55)
s = pd.Series(arr, dtype='float32')
print(s)

0    50.0
1    51.0
2    52.0
3    53.0
4    54.0
dtype: float32


In [39]:
f = ['바나나', np.nan, '사과', '포도', '복숭아']
s = pd.Series(f, index=(list('가나다라마')))
print(s)

가    바나나
나    NaN
다     사과
라     포도
마    복숭아
dtype: object


### fanch indexing

In [43]:
s[['다', '나']]

다     사과
나    NaN
dtype: object

In [45]:
s.iloc[[2, 3]]

다    사과
라    포도
dtype: object

### bool

In [46]:
s[[True, False, True, False, True]]

가    바나나
다     사과
마    복숭아
dtype: object

In [47]:
a = [True, False, False, True, True]
s[a]

가    바나나
라     포도
마    복숭아
dtype: object

In [48]:
arr = np.arange(5, 20)
s = pd.Series(arr)
print(s)

0      5
1      6
2      7
3      8
4      9
5     10
6     11
7     12
8     13
9     14
10    15
11    16
12    17
13    18
14    19
dtype: int64


In [49]:
s < 10

0      True
1      True
2      True
3      True
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [50]:
s[s < 10]

0    5
1    6
2    7
3    8
4    9
dtype: int64

In [51]:
s[s == 5]

0    5
dtype: int64

## 결측치(NaN) 처리 

In [53]:
s = pd.Series([1, 2, 3, np.nan, 3, 4, 9, np.nan, 4, 7])
print(s)

0    1.0
1    2.0
2    3.0
3    NaN
4    3.0
5    4.0
6    9.0
7    NaN
8    4.0
9    7.0
dtype: float64


In [55]:
s.isnull() # 시리즈목록에서 null인 데이터 목록 출력

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7     True
8    False
9    False
dtype: bool

In [56]:
s[s.isnull()]

3   NaN
7   NaN
dtype: float64

In [57]:
s.isna()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7     True
8    False
9    False
dtype: bool

In [58]:
s[s.isna()]

3   NaN
7   NaN
dtype: float64

In [61]:
s.notnull() # 결측치 제외 데이터 True

0     True
1     True
2     True
3    False
4     True
5     True
6     True
7    False
8     True
9     True
dtype: bool

In [62]:
s[s.notnull()]

0    1.0
1    2.0
2    3.0
4    3.0
5    4.0
6    9.0
8    4.0
9    7.0
dtype: float64

In [63]:
s[1:3]

1    2.0
2    3.0
dtype: float64

## DataFrame

In [64]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [67]:
df = pd.DataFrame(arr)
df

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [68]:
df = pd.DataFrame(arr,
                  columns=['가', '나', '다'],
                  index=['a', 'b', 'c'])
df

가  나  다
a  0  1  2
b  3  4  5
c  6  7  8

In [69]:
data = {
    'name': ['kim', 'lee', 'park'],
    'age': [10, 15, 20],
    'location': ['seoul', 'LA', 'tokyo'] 
}
df = pd.DataFrame(data)
df

name  age location
0   kim   10    seoul
1   lee   15       LA
2  park   20    tokyo

In [70]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [71]:
df.columns

Index(['name', 'age', 'location'], dtype='object')

In [72]:
df.values

array([['kim', 10, 'seoul'],
       ['lee', 15, 'LA'],
       ['park', 20, 'tokyo']], dtype=object)

In [74]:
df.dtypes #column을 기준으로 속성 출력

name        object
age          int64
location    object
dtype: object

In [75]:
df.T

0    1      2
name        kim  lee   park
age          10   15     20
location  seoul   LA  tokyo

In [76]:
df

name  age location
0   kim   10    seoul
1   lee   15       LA
2  park   20    tokyo

In [77]:
df.index = list('abc')
df

name  age location
a   kim   10    seoul
b   lee   15       LA
c  park   20    tokyo

### column

In [78]:
df['name']

a     kim
b     lee
c    park
Name: name, dtype: object

In [79]:
type(df['name'])

pandas.core.series.Series

In [80]:
df[['name', 'location']]

name location
a   kim    seoul
b   lee       LA
c  park    tokyo

In [81]:
type(df[['name', 'location']])

pandas.core.frame.DataFrame

In [92]:
# df = df.rename(columns={'location': 'hometown'}) #원본이 바뀌지 않음 바꾸려면 변수에 재할당 또는 inplace=True
df.rename(columns={'location': 'hometown'}, inplace=True)
df

name  age hometown
a   kim   10    seoul
b   lee   15       LA
c  park   20    tokyo